<?php

/*
    List:
    1. Globals
    2. Wordpress
    3. Theme specific
    4. Plugins
    5. Custom libraries
   */

/* ----------------------------------*/
/* ------------ GLOBALS -------------*/
/* ----------------------------------*/

$themeENV = parse_ini_file(".env");

global $themeSetup;
$themeSetup = [

  'projectName' => $themeENV['THEME_NAME'],
  'projectNameLower' => $themeENV['THEME_NAME_LOWERCASE'],
  'projectNameLong' => $themeENV['THEME_NAME_LONG'],

  // Manifest JSON data for auto-loading of scripts and styles
  'viteManifest' => json_decode(file_get_contents(get_template_directory() . '/assets/_autoGenerated/manifest.json'), true),

  // Global theme settings page from WP admin
  'options' => [
    'globalComponents' => []
  ],

  // API Keys
  'googleMapsAPIKey' => $themeENV['GOOGLEMAPS_API_KEY'],

  // WP Tweaks
  'wpTweaks' => [
    'fixFileUploadNames' => boolval($themeENV['TWEAK_FIX_FILE_UPLOAD_NAMES']),
    'removeWPEmbeds' => boolval($themeENV['TWEAK_REMOVE_WP_EMBEDS']),
    'removeSRCsetGeneration' => boolval($themeENV['TWEAK_REMOVE_SRCSET_GENERATION']),
    'removeCommentsFromAdmin' => boolval($themeENV['TWEAK_REMOVE_COMMENTS_FROM_ADMIN']),
    'removeStandardWPPosts' => boolval($themeENV['TWEAK_REMOVE_STANDARD_WP_POSTS']),
    'addFrontendjQuery' => boolval($themeENV['TWEAK_ADD_FRONTEND_JQUERY'])
  ],
  'pluginTweaks' => [
    'useLocalACF' => boolval($themeENV['ACF_USE_LOCAL']),
    'useLocalACFOptionsPage' => boolval($themeENV['ACF_USE_OPTION_PAGE']),
    'contactForm7removePadding' => boolval($themeENV['CF7_REMOVE_PADDINGS']),
    'useClassicEditor' => boolval($themeENV['USE_CLASSIC_EDITOR']),
    'suggestTweakPlugins' => boolval($themeENV['SUGGEST_TWEAK_PLUGGINS']),
  ]
];


/* -------------------------------------*/
/* ------------ WP: TWEAKS -------------*/
/* -------------------------------------*/

// Fix non-ASCII characters in uploaded files
if ($themeSetup['wpTweaks']['fixFileUploadNames'] == true) {
  include_once "added-functionality/wpTweaks/removeNonAsciiCharsFromFileUpload.php";
  add_filter('sanitize_file_name', 'removeNonAsciiCharsFromFileUpload', 10);
}

// Remove WP embeds
if ($themeSetup['wpTweaks']['removeWPEmbeds'] == true) {
  include_once "added-functionality/wpTweaks/removeWPEmbed.php";
  removeWPEmbed();
}

// Remove WP SRCset generation for easier image handling
if ($themeSetup['wpTweaks']['removeSRCsetGeneration'] == true) {
  add_filter('wp_calculate_image_srcset', '__return_false');
}

// Remove comments from administration
if ($themeSetup['wpTweaks']['removeCommentsFromAdmin'] == true) {
  include_once "added-functionality/wpTweaks/removeCommentsFromAdmin.php";
  removeCommentsFromAdmin();
}

// Remove default WP post types from admin
if ($themeSetup['wpTweaks']['removeStandardWPPosts'] == true) {
  include_once "added-functionality/wpTweaks/removeStandardWPPosts.php";
  removeStandardWPPosts();
}

// Add jQuery for frontend purposes
if ($themeSetup['wpTweaks']['addFrontendjQuery'] == true) {
  function addjQuery() {
    wp_enqueue_script('jquery');
  }
  add_action('wp_enqueue_scripts', 'addjQuery');
}


/* ------------------------------------------------*/
/* ----------- THEME: ADD CUSTOM MENUS ------------*/
/* ------------------------------------------------*/

// Register custom menus
include_once "added-functionality/wpMenus/registerCustomMenus.php";
add_action('init', 'registerMenus');


/* --------------------------------------------------------------*/
/* ----------- THEME: CUSTOM POST TYPES & TAXONOMIES ------------*/
/* --------------------------------------------------------------*/

// Add custom post types
include_once "added-functionality/customPostTypes/registerCustomPostTypes.php";
registerCustomPostTypes();

// Add custom taxonomies
include_once "added-functionality/customPostTypes/registerCustomCategories.php";
registerCustomCategories();

/* ----------------------------------------------------------*/
/* ----------- THEME: LOAD VITE SCRIPTS & STYLES ------------*/
/* ----------------------------------------------------------*/

// Add VITE script file
function addjViteScripts() {
  global $themeSetup;
  $fileName = $themeSetup['viteManifest']['_src/main.ts']['file'];
  wp_enqueue_script('elvthememainscript', get_template_directory_uri() . '/assets/_autoGenerated/' . $fileName, [], null, true);
}
addjViteScripts();

// Add VITE style file
function addjViteStyles() {
  global $themeSetup;
  $fileName = $themeSetup['viteManifest']['_src/main.css']['file'];
  wp_enqueue_style('elvthememainstyles', get_template_directory_uri() . '/assets/_autoGenerated/' . $fileName, [], null);
}
addjViteStyles();


/* --------------------------------------------------*/
/* ------------ PLUGIN: PLUGIN ACTIVATOR ------------*/
/* --------------------------------------------------*/

// Load plugin activator
include_once "added-functionality/pluginActivator/addPluginActivator.php";


/* -----------------------------------------------------*/
/* ------------- PLUGIN: ACF & ACF Extended ------------*/
/* -----------------------------------------------------*/

// Add local ACF plugin
if ($themeSetup['pluginTweaks']['useLocalACF'] == true) {
  include_once "added-functionality/acf/acfLocal.php";
  addAcfLocal();
}

// Add local ACF Extended plugin
if ($themeSetup['pluginTweaks']['useLocalACF'] == true) {
  include_once "added-functionality/acf/acfExtendedLocal.php";
  addAcfExtendedLocal();
}

// Add ACF custom google maps key
if ($themeSetup['pluginTweaks']['useLocalACF'] == true) {
  include_once "added-functionality/acf/acfGoogleMapsKey.php";
  add_action('acf/init', 'customGoogleMapsKey');
}

// Register ACF function pages
if ($themeSetup['pluginTweaks']['useLocalACF'] == true && $themeSetup['pluginTweaks']['useLocalACFOptionsPage'] == true) {
  include_once "added-functionality/acf/acfRegisterOptionsPages.php";
  acfRegisterOptionsPages();
}


// Load correct ACF settings page
if ($themeSetup['pluginTweaks']['useLocalACF'] == true && $themeSetup['pluginTweaks']['useLocalACFOptionsPage'] == true) {
  include_once "added-functionality/acf/acfReadSpecificOptionsPage.php";
  add_action('acf/init', 'acfReadSpecificOptionsPage', 1, 0);
}


/* --------------------------------------------------*/
/* ------------ PLUGIN: CONTACT FORM 7 --------------*/
/* --------------------------------------------------*/

// Fix formatting and styles of contact form 7 (assuming the theme is using it)
if ($themeSetup['pluginTweaks']['contactForm7removePadding'] == true) {
  include_once "added-functionality/contactForm7/removeStylesAndPadding.php";
  removeStylesAndPadding();
}


/* -------------------------------------------------*/
/* ------------ CUSTOM: IMAGE HELPERS --------------*/
/* -------------------------------------------------*/

// Add Aqua Resizer
include_once "added-functionality/imageHelpers/customImageResizer.php";
addAquaResizer();
