import { defineConfig } from 'vite'
import { resolve } from 'path'
import { rm } from 'node:fs/promises'

export default defineConfig({
  
  // Vite general build config
  build: {

    // Input and ouput dir configs
    outDir: resolve(__dirname, 'assets/_autoGenerated'),
    assetsDir: '',
    rollupOptions: {
      input: { 
        main: resolve( __dirname + '/_src/main.ts')
      },
    },

    // Builder config
    target: 'es2018',
    emptyOutDir: false,
    minify: false,
    write: true,

    // Extra config for backend
    manifest: true,
    sourcemap: true
  },

  // Extra custom plugins for needed functionality
  plugins: [
    {
      name: "Empty _autoGenerated folder",
      async buildStart() {
        await rm(resolve(__dirname + '/assets/_autoGenerated'), { recursive: true, force: true })
      }
    }
  ],

})